### PR TITLE
skbeam v0.0.12

### PR DESCRIPTION
**Pull request by licode**
xraylib windows version is ready, so remove dependences on that.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Do we want a re-render for numpy 1.13?

**Comment by licode** [comment]
added numpy 1.13 and removed old version 1.11.

**Comment by CJ-Wright** [comment]
Are we going to drop support for py27?

**Comment by licode** [comment]
We will keep py27. I am working on a pr to fix this and some other issues, then I will do some cleanup here.

**Comment by CJ-Wright** [comment]
It's a bit odd that it only broke on circle.

**Comment by CJ-Wright** [comment]
Being addressed in https://github.com/scikit-beam/scikit-beam/issues/509

**Comment by ericdill** [comment]
@CJ-Wright FWIW the travis-ci 2.7 build did "break" but the job didn't fail. There's this nugget in the logs:

```
INFO:conda_build.build:Packaging scikit-beam-0.0.11-np111py27_0
compiling .pyc files...
  File "lib/python2.7/site-packages/skbeam/core/correlation.py", line 1164
    .format(*img1.shape, *img2.shape)
                         ^
SyntaxError: invalid syntax
```

Not 100% sure why this didn't fail the job. In any event, we should probably wait until the linked PR is finished and make a new release for skbeam

**Comment by CJ-Wright** [comment]
Hmm, that's odd you'd think that would fail the job

**Comment by licode** [comment]
ready to go?

**Comment by licode** [comment]
self merged.

**Pull request merged**
