### PR TITLE
bumped scikit-beam

### PR DESCRIPTION
**Pull request by jrmlhermitte**
bump scikit-beam

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
@CJ-Wright

**Comment by CJ-Wright** [comment]
@jrmlhermitte can you address the linter's comments?

**Comment by jrmlhermitte** [comment]
ok sounds good. so `numpy x.x` is deprecated. I switched to `numpy >= 1.13`. We're compatible with older versions but let's just stick with more recent versions anyway.

**Comment by jrmlhermitte** [comment]
actually changed to `numpy 1.11` just to remain consistent with what `numpy x.x` signified.

**Comment by CJ-Wright** [comment]
@jrmlhermitte can we move this to just a linux build? It seems windows is having an issue and Travis OSX is moving at molasses pace. https://www.traviscistatus.com/
We can put in a PR right after that one which puts the windows and OSX builds back.

**Comment by jrmlhermitte** [comment]
ok im not sure how to do it but i assumed you knew and dug around your lib [here](https://github.com/conda-forge/xpdsim-feedstock/commit/25591f15d9c67726076dbf95eb65b02544a5f9b5). Is that right?
Waiting for appveyor

**Comment by CJ-Wright** [comment]
You don't need to remove the files, you just need to rerender the feedstock.

**Comment by CJ-Wright** [comment]
Don't worry I've got it.

**Comment by jrmlhermitte** [comment]
ok just edited it

**Comment by CJ-Wright** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
@jrmlhermitte that request updates the feedstock and removes unused builds.

**Comment by jrmlhermitte** [comment]
that is awesome

**Comment by CJ-Wright** [comment]
Thank you @jrmlhermitte

**Comment by jrmlhermitte** [comment]
yay!!! (we can finally use some of the many new features...)

We should work on release notes between 0.0.12 and 0.0.13 as there were quire some changes

**Pull request merged**
